### ISSUE TITLE
Guzzle requirement

### ISSUE THREAD

**Issue by chadpriddle** [yajra/zillow#1]
I am using laravel 5.1 and in composer I am using this: "guzzlehttp/guzzle": "~5.3|~6.0"

I get this error: yajra/zillow v2.0.2 requires guzzlehttp/guzzle 4.\* -> no matching package found. Should this script be updated to use a newer version of guzzle? Or?

**Comment by yajra** [comment]
Thanks for reporting. I updated composer and allowed Guzzle 4|5|6. Released on v2.0.3

**Comment by santiagazo** [comment]
I'm using Laravel 5.2 and I tried to composer require this and got this error...

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yajra/zillow v2.0.2 requires guzzlehttp/guzzle 4.\* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev] **but these conflict with your requirements or minimum-stability.**
    - yajra/zillow v2.0.1 requires guzzlehttp/guzzle 4.\* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev] **but these conflict with your requirements or minimum-stability.**
    - fabpot/goutte v2.0.2 requires guzzlehttp/guzzle 4.\* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev] **but these conflict with your requirements or minimum-stability.**
    - fabpot/goutte v2.0.1 requires guzzlehttp/guzzle 4.\* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev] **but these conflict with your requirements or minimum-stability.**
    - fabpot/goutte v2.0.0 requires guzzlehttp/guzzle 4.\* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev] **but these conflict with your requirements or minimum-stability.**
    - yajra/zillow v2.0.0 requires guzzlehttp/guzzle 4.\* -> satisfiable by guzzlehttp/guzzle[4.0.0, 4.0.0-rc.1, 4.0.0-rc.2, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.1.8, 4.2.0, 4.2.1, 4.2.2, 4.2.3, 4.2.4, 4.x-dev] **but these conflict with your requirements or minimum-stability.**
    - Installation request for yajra/zillow ~2.0 -> satisfiable by yajra/zillow[v2.0.0, v2.0.1, v2.0.2, v2.0.3].
    - Conclusion: remove symfony/css-selector v3.0.9
    - Conclusion: don't install symfony/css-selector v3.0.9
    - yajra/zillow v2.0.3 requires fabpot/goutte ~2.0 -> satisfiable by fabpot/goutte[v2.0.0, v2.0.1, v2.0.2, v2.0.3, v2.0.4].
    - fabpot/goutte v2.0.3 requires symfony/css-selector ~2.1 -> satisfiable by symfony/css-selector[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - fabpot/goutte v2.0.4 requires symfony/css-selector ~2.1 -> satisfiable by symfony/css-selector[v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.2, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - Can only install one of: symfony/css-selector[v2.8.0, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.1, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.10, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.11, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.2, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.3, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.4, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.5, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.6, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.7, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.8, v3.0.9].
    - Can only install one of: symfony/css-selector[v2.8.9, v3.0.9].
    - Installation request for symfony/css-selector (locked at v3.0.9, required as 2.8._|3.0._) -> satisfiable by symfony/css-selector[v3.0.9].

## **Installation failed, reverting ./composer.json to its original content.**

Is this something I need to fix on my side or is this needing an update on the code's side?

**Comment by yajra** [comment]
@santiagazo I haven't tried this yet on 5.2. 

Anyways, thanks for reporting. Will upgrade the package to support 5.2 & 5.3 when I had the chance.

**Comment by santiagazo** [comment]
Thanks so much. LMK if you do!
